# SPDX-License-Identifier: GPL-2.0-only
# This file is part of Scapy RPC
# See https://scapy.net/ for more information
# Copyright (C) Gabriel Potter

# [ms-bkrp] v27.0 (Tue, 23 Apr 2024)

"""
RPC definitions for the following interfaces:
- BackupKey (v1.0): 3dde7c30-165d-11d1-ab8f-00805f14db40
This file is auto-generated by midl-to-scapy, do not modify.
"""

import uuid

from scapy.fields import StrFixedLenField
from scapy.layers.dcerpc import (
    NDRPacket,
    DceRpcOp,
    NDRConfFieldListField,
    NDRConfStrLenField,
    NDRFullPointerField,
    NDRIntField,
    NDRPacketField,
    NDRShortField,
    NDRSignedByteField,
    register_dcerpc_interface,
)


class GUID(NDRPacket):
    ALIGNMENT = (4, 4)
    fields_desc = [
        NDRIntField("Data1", 0),
        NDRShortField("Data2", 0),
        NDRShortField("Data3", 0),
        StrFixedLenField("Data4", "", length=8),
    ]


class BackuprKey_Request(NDRPacket):
    fields_desc = [
        NDRPacketField("pguidActionAgent", GUID(), GUID),
        NDRConfStrLenField("pDataIn", "", size_is=lambda pkt: pkt.cbDataIn),
        NDRIntField("cbDataIn", None, size_of="pDataIn"),
        NDRIntField("dwParam", 0),
    ]


class BackuprKey_Response(NDRPacket):
    fields_desc = [
        NDRConfFieldListField(
            "ppDataOut",
            [],
            NDRFullPointerField(NDRSignedByteField("", 0)),
            size_is=lambda pkt: pkt.pcbDataOut,
            ptr_pack=True,
        ),
        NDRIntField("pcbDataOut", None, size_of="ppDataOut"),
        NDRIntField("status", 0),
    ]


BACKUPKEY_OPNUMS = {0: DceRpcOp(BackuprKey_Request, BackuprKey_Response)}
register_dcerpc_interface(
    name="BackupKey",
    uuid=uuid.UUID("3dde7c30-165d-11d1-ab8f-00805f14db40"),
    version="1.0",
    opnums=BACKUPKEY_OPNUMS,
)
