# SPDX-License-Identifier: GPL-2.0-only
# This file is part of Scapy RPC
# See https://scapy.net/ for more information
# Copyright (C) Gabriel Potter

# [ms-eerr] v16.0 (Tue, 23 Apr 2024)

"""
RPC definitions for the following interfaces:
- ExtendedError (v1.0): 14a8831c-bc82-11d2-8a64-0008c7457e5d
This file is auto-generated by midl-to-scapy, do not modify.
"""

import uuid


from scapy.layers.dcerpc import NDRPacket, register_dcerpc_interface

EXTENDEDERROR_OPNUMS = {}
register_dcerpc_interface(
    name="ExtendedError",
    uuid=uuid.UUID("14a8831c-bc82-11d2-8a64-0008c7457e5d"),
    version="1.0",
    opnums=EXTENDEDERROR_OPNUMS,
)
