# SPDX-License-Identifier: GPL-2.0-only
# This file is part of Scapy RPC
# See https://scapy.net/ for more information
# Copyright (C) Gabriel Potter

# [ms-imsa] v16.0 (Tue, 23 Apr 2024)

"""
RPC definitions for the following interfaces:
- IUnknown (v0.0): 00000000-0000-0000-C000-000000000046
- IMSAdminBaseW (v0.0): 70B51430-B6CA-11d0-B9B9-00A0C922E750
- IMSAdminBase2W (v0.0): 8298d101-f992-43b7-8eca-5052d885b995
- IMSAdminBase3W (v0.0): f612954d-3b0b-4c56-9563-227b7be624b4
- IWamAdmin (v0.0): 29822AB7-F302-11D0-9953-00C04FD919C1
- IWamAdmin2 (v0.0): 29822AB8-F302-11D0-9953-00C04FD919C1
- IIISApplicationAdmin (v0.0): 7C4E1804-E342-483D-A43E-A850CFCC8D18
- IDispatch (v0.0): 00020400-0000-0000-C000-000000000046
- IIISCertObj (v0.0): BD0C73BC-805B-4043-9C30-9A28D64DD7D2
This file is auto-generated by midl-to-scapy, do not modify.
"""

from enum import IntEnum
import uuid

from scapy.fields import StrFixedLenField
from scapy.layers.dcerpc import (
    NDRPacket,
    DceRpcOp,
    NDRConfFieldListField,
    NDRConfPacketListField,
    NDRConfStrLenField,
    NDRConfStrLenFieldUtf16,
    NDRConfVarStrLenField,
    NDRConfVarStrLenFieldUtf16,
    NDRConfVarStrNullField,
    NDRConfVarStrNullFieldUtf16,
    NDRFullEmbPointerField,
    NDRFullPointerField,
    NDRIEEEDoubleField,
    NDRIEEEFloatField,
    NDRInt3264Field,
    NDRIntField,
    NDRLongField,
    NDRPacketField,
    NDRRecursiveClass,
    NDRRefEmbPointerField,
    NDRShortField,
    NDRSignedByteField,
    NDRSignedIntField,
    NDRSignedLongField,
    NDRSignedShortField,
    NDRUnionField,
    register_com_interface,
    register_dcerpc_interface,
)

IUNKNOWN_OPNUMS = {  # 0: Opnum0NotUsedOnWire,
    # 1: Opnum1NotUsedOnWire,
    # 2: Opnum2NotUsedOnWire
}
register_com_interface(
    name="IUnknown",
    uuid=uuid.UUID("00000000-0000-0000-C000-000000000046"),
    opnums=IUNKNOWN_OPNUMS,
)


class AddKey_Request(NDRPacket):
    fields_desc = [
        NDRIntField("hMDHandle", 0),
        NDRFullPointerField(NDRConfVarStrNullFieldUtf16("pszMDPath", "")),
    ]


class AddKey_Response(NDRPacket):
    fields_desc = [NDRIntField("status", 0)]


class DeleteKey_Request(NDRPacket):
    fields_desc = [
        NDRIntField("hMDHandle", 0),
        NDRFullPointerField(NDRConfVarStrNullFieldUtf16("pszMDPath", "")),
    ]


class DeleteKey_Response(NDRPacket):
    fields_desc = [NDRIntField("status", 0)]


class DeleteChildKeys_Request(NDRPacket):
    fields_desc = [
        NDRIntField("hMDHandle", 0),
        NDRFullPointerField(NDRConfVarStrNullFieldUtf16("pszMDPath", "")),
    ]


class DeleteChildKeys_Response(NDRPacket):
    fields_desc = [NDRIntField("status", 0)]


class EnumKeys_Request(NDRPacket):
    fields_desc = [
        NDRIntField("hMDHandle", 0),
        NDRFullPointerField(NDRConfVarStrNullFieldUtf16("pszMDPath", "")),
        NDRIntField("dwMDEnumObjectIndex", 0),
    ]


class EnumKeys_Response(NDRPacket):
    fields_desc = [
        NDRConfFieldListField(
            "pszMDName",
            [],
            NDRShortField("", 0),
            size_is=lambda pkt: pkt.ADMINDATA_MAX_NAME_LEN,
        ),
        NDRIntField("status", 0),
    ]


class CopyKey_Request(NDRPacket):
    fields_desc = [
        NDRIntField("hMDSourceHandle", 0),
        NDRFullPointerField(NDRConfVarStrNullFieldUtf16("pszMDSourcePath", "")),
        NDRIntField("hMDDestHandle", 0),
        NDRFullPointerField(NDRConfVarStrNullFieldUtf16("pszMDDestPath", "")),
        NDRSignedIntField("bMDOverwriteFlag", 0),
        NDRSignedIntField("bMDCopyFlag", 0),
    ]


class CopyKey_Response(NDRPacket):
    fields_desc = [NDRIntField("status", 0)]


class RenameKey_Request(NDRPacket):
    fields_desc = [
        NDRIntField("hMDHandle", 0),
        NDRFullPointerField(NDRConfVarStrNullFieldUtf16("pszMDPath", "")),
        NDRFullPointerField(NDRConfVarStrNullFieldUtf16("pszMDNewName", "")),
    ]


class RenameKey_Response(NDRPacket):
    fields_desc = [NDRIntField("status", 0)]


class METADATA_RECORD(NDRPacket):
    ALIGNMENT = (4, 8)
    fields_desc = [
        NDRIntField("dwMDIdentifier", 0),
        NDRIntField("dwMDAttributes", 0),
        NDRIntField("dwMDUserType", 0),
        NDRIntField("dwMDDataType", 0),
        NDRIntField("dwMDDataLen", None, size_of="pbMDData"),
        NDRFullEmbPointerField(
            NDRConfStrLenField("pbMDData", "", size_is=lambda pkt: pkt.dwMDDataLen)
        ),
        NDRIntField("dwMDDataTag", 0),
    ]


class R_SetData_Request(NDRPacket):
    fields_desc = [
        NDRIntField("hMDHandle", 0),
        NDRFullPointerField(NDRConfVarStrNullFieldUtf16("pszMDPath", "")),
        NDRPacketField("pmdrMDData", METADATA_RECORD(), METADATA_RECORD),
    ]


class R_SetData_Response(NDRPacket):
    fields_desc = [NDRIntField("status", 0)]


class IIS_CRYPTO_BLOB(NDRPacket):
    ALIGNMENT = (4, 4)
    DEPORTED_CONFORMANTS = ["BlobData"]
    fields_desc = [
        NDRIntField("BlobSignature", 0),
        NDRIntField("BlobDataLength", None, size_of="BlobData"),
        NDRConfStrLenField(
            "BlobData",
            "",
            size_is=lambda pkt: pkt.BlobDataLength,
            conformant_in_struct=True,
        ),
    ]


class R_GetData_Request(NDRPacket):
    fields_desc = [
        NDRIntField("hMDHandle", 0),
        NDRFullPointerField(NDRConfVarStrNullFieldUtf16("pszMDPath", "")),
        NDRPacketField("pmdrMDData", METADATA_RECORD(), METADATA_RECORD),
    ]


class R_GetData_Response(NDRPacket):
    fields_desc = [
        NDRPacketField("pmdrMDData", METADATA_RECORD(), METADATA_RECORD),
        NDRIntField("pdwMDRequiredDataLen", 0),
        NDRFullPointerField(
            NDRPacketField("ppDataBlob", IIS_CRYPTO_BLOB(), IIS_CRYPTO_BLOB)
        ),
        NDRIntField("status", 0),
    ]


class DeleteData_Request(NDRPacket):
    fields_desc = [
        NDRIntField("hMDHandle", 0),
        NDRFullPointerField(NDRConfVarStrNullFieldUtf16("pszMDPath", "")),
        NDRIntField("dwMDIdentifier", 0),
        NDRIntField("dwMDDataType", 0),
    ]


class DeleteData_Response(NDRPacket):
    fields_desc = [NDRIntField("status", 0)]


class R_EnumData_Request(NDRPacket):
    fields_desc = [
        NDRIntField("hMDHandle", 0),
        NDRFullPointerField(NDRConfVarStrNullFieldUtf16("pszMDPath", "")),
        NDRPacketField("pmdrMDData", METADATA_RECORD(), METADATA_RECORD),
        NDRIntField("dwMDEnumDataIndex", 0),
    ]


class R_EnumData_Response(NDRPacket):
    fields_desc = [
        NDRPacketField("pmdrMDData", METADATA_RECORD(), METADATA_RECORD),
        NDRIntField("pdwMDRequiredDataLen", 0),
        NDRFullPointerField(
            NDRPacketField("ppDataBlob", IIS_CRYPTO_BLOB(), IIS_CRYPTO_BLOB)
        ),
        NDRIntField("status", 0),
    ]


class R_GetAllData_Request(NDRPacket):
    fields_desc = [
        NDRIntField("hMDHandle", 0),
        NDRFullPointerField(NDRConfVarStrNullFieldUtf16("pszMDPath", "")),
        NDRIntField("dwMDAttributes", 0),
        NDRIntField("dwMDUserType", 0),
        NDRIntField("dwMDDataType", 0),
        NDRIntField("dwMDBufferSize", 0),
    ]


class R_GetAllData_Response(NDRPacket):
    fields_desc = [
        NDRIntField("pdwMDNumDataEntries", 0),
        NDRIntField("pdwMDDataSetNumber", 0),
        NDRIntField("pdwMDRequiredBufferSize", 0),
        NDRFullPointerField(
            NDRPacketField("ppDataBlob", IIS_CRYPTO_BLOB(), IIS_CRYPTO_BLOB)
        ),
        NDRIntField("status", 0),
    ]


class DeleteAllData_Request(NDRPacket):
    fields_desc = [
        NDRIntField("hMDHandle", 0),
        NDRFullPointerField(NDRConfVarStrNullFieldUtf16("pszMDPath", "")),
        NDRIntField("dwMDUserType", 0),
        NDRIntField("dwMDDataType", 0),
    ]


class DeleteAllData_Response(NDRPacket):
    fields_desc = [NDRIntField("status", 0)]


class CopyData_Request(NDRPacket):
    fields_desc = [
        NDRIntField("hMDSourceHandle", 0),
        NDRFullPointerField(NDRConfVarStrNullFieldUtf16("pszMDSourcePath", "")),
        NDRIntField("hMDDestHandle", 0),
        NDRFullPointerField(NDRConfVarStrNullFieldUtf16("pszMDDestPath", "")),
        NDRIntField("dwMDAttributes", 0),
        NDRIntField("dwMDUserType", 0),
        NDRIntField("dwMDDataType", 0),
        NDRSignedIntField("bMDCopyFlag", 0),
    ]


class CopyData_Response(NDRPacket):
    fields_desc = [NDRIntField("status", 0)]


class GetDataPaths_Request(NDRPacket):
    fields_desc = [
        NDRIntField("hMDHandle", 0),
        NDRFullPointerField(NDRConfVarStrNullFieldUtf16("pszMDPath", "")),
        NDRIntField("dwMDIdentifier", 0),
        NDRIntField("dwMDDataType", 0),
        NDRIntField("dwMDBufferSize", 0),
    ]


class GetDataPaths_Response(NDRPacket):
    fields_desc = [
        NDRConfStrLenFieldUtf16(
            "pszBuffer", "", size_is=lambda pkt: pkt.dwMDBufferSize
        ),
        NDRIntField("pdwMDRequiredBufferSize", 0),
        NDRIntField("status", 0),
    ]


class OpenKey_Request(NDRPacket):
    fields_desc = [
        NDRIntField("hMDHandle", 0),
        NDRFullPointerField(NDRConfVarStrNullFieldUtf16("pszMDPath", "")),
        NDRIntField("dwMDAccessRequested", 0),
        NDRIntField("dwMDTimeOut", 0),
    ]


class OpenKey_Response(NDRPacket):
    fields_desc = [NDRIntField("phMDNewHandle", 0), NDRIntField("status", 0)]


class CloseKey_Request(NDRPacket):
    fields_desc = [NDRIntField("hMDHandle", 0)]


class CloseKey_Response(NDRPacket):
    fields_desc = [NDRIntField("status", 0)]


class ChangePermissions_Request(NDRPacket):
    fields_desc = [
        NDRIntField("hMDHandle", 0),
        NDRIntField("dwMDTimeOut", 0),
        NDRIntField("dwMDAccessRequested", 0),
    ]


class ChangePermissions_Response(NDRPacket):
    fields_desc = [NDRIntField("status", 0)]


class SaveData_Request(NDRPacket):
    fields_desc = []


class SaveData_Response(NDRPacket):
    fields_desc = [NDRIntField("status", 0)]


class METADATA_HANDLE_INFO(NDRPacket):
    ALIGNMENT = (4, 4)
    fields_desc = [
        NDRIntField("dwMDPermissions", 0),
        NDRIntField("dwMDSystemChangeNumber", 0),
    ]


class GetHandleInfo_Request(NDRPacket):
    fields_desc = [NDRIntField("hMDHandle", 0)]


class GetHandleInfo_Response(NDRPacket):
    fields_desc = [
        NDRPacketField("pmdhiInfo", METADATA_HANDLE_INFO(), METADATA_HANDLE_INFO),
        NDRIntField("status", 0),
    ]


class GetSystemChangeNumber_Request(NDRPacket):
    fields_desc = []


class GetSystemChangeNumber_Response(NDRPacket):
    fields_desc = [NDRIntField("pdwSystemChangeNumber", 0), NDRIntField("status", 0)]


class GetDataSetNumber_Request(NDRPacket):
    fields_desc = [
        NDRIntField("hMDHandle", 0),
        NDRFullPointerField(NDRConfVarStrNullFieldUtf16("pszMDPath", "")),
    ]


class GetDataSetNumber_Response(NDRPacket):
    fields_desc = [NDRIntField("pdwMDDataSetNumber", 0), NDRIntField("status", 0)]


class PFILETIME(NDRPacket):
    ALIGNMENT = (4, 4)
    fields_desc = [NDRIntField("dwLowDateTime", 0), NDRIntField("dwHighDateTime", 0)]


class SetLastChangeTime_Request(NDRPacket):
    fields_desc = [
        NDRIntField("hMDHandle", 0),
        NDRFullPointerField(NDRConfVarStrNullFieldUtf16("pszMDPath", "")),
        NDRPacketField("pftMDLastChangeTime", PFILETIME(), PFILETIME),
        NDRSignedIntField("bLocalTime", 0),
    ]


class SetLastChangeTime_Response(NDRPacket):
    fields_desc = [NDRIntField("status", 0)]


class GetLastChangeTime_Request(NDRPacket):
    fields_desc = [
        NDRIntField("hMDHandle", 0),
        NDRFullPointerField(NDRConfVarStrNullFieldUtf16("pszMDPath", "")),
        NDRSignedIntField("bLocalTime", 0),
    ]


class GetLastChangeTime_Response(NDRPacket):
    fields_desc = [
        NDRPacketField("pftMDLastChangeTime", PFILETIME(), PFILETIME),
        NDRIntField("status", 0),
    ]


class R_KeyExchangePhase1_Request(NDRPacket):
    fields_desc = [
        NDRFullPointerField(
            NDRPacketField(
                "pClientKeyExchangeKeyBlob", IIS_CRYPTO_BLOB(), IIS_CRYPTO_BLOB
            )
        ),
        NDRFullPointerField(
            NDRPacketField(
                "pClientSignatureKeyBlob", IIS_CRYPTO_BLOB(), IIS_CRYPTO_BLOB
            )
        ),
    ]


class R_KeyExchangePhase1_Response(NDRPacket):
    fields_desc = [
        NDRFullPointerField(
            NDRPacketField(
                "ppServerKeyExchangeKeyBlob", IIS_CRYPTO_BLOB(), IIS_CRYPTO_BLOB
            )
        ),
        NDRFullPointerField(
            NDRPacketField(
                "ppServerSignatureKeyBlob", IIS_CRYPTO_BLOB(), IIS_CRYPTO_BLOB
            )
        ),
        NDRFullPointerField(
            NDRPacketField("ppServerSessionKeyBlob", IIS_CRYPTO_BLOB(), IIS_CRYPTO_BLOB)
        ),
        NDRIntField("status", 0),
    ]


class R_KeyExchangePhase2_Request(NDRPacket):
    fields_desc = [
        NDRFullPointerField(
            NDRPacketField("pClientSessionKeyBlob", IIS_CRYPTO_BLOB(), IIS_CRYPTO_BLOB)
        ),
        NDRFullPointerField(
            NDRPacketField("pClientHashBlob", IIS_CRYPTO_BLOB(), IIS_CRYPTO_BLOB)
        ),
    ]


class R_KeyExchangePhase2_Response(NDRPacket):
    fields_desc = [
        NDRFullPointerField(
            NDRPacketField("ppServerHashBlob", IIS_CRYPTO_BLOB(), IIS_CRYPTO_BLOB)
        ),
        NDRIntField("status", 0),
    ]


class Backup_Request(NDRPacket):
    fields_desc = [
        NDRFullPointerField(NDRConfVarStrNullFieldUtf16("pszMDBackupName", "")),
        NDRIntField("dwMDVersion", 0),
        NDRIntField("dwMDFlags", 0),
    ]


class Backup_Response(NDRPacket):
    fields_desc = [NDRIntField("status", 0)]


class Restore_Request(NDRPacket):
    fields_desc = [
        NDRFullPointerField(NDRConfVarStrNullFieldUtf16("pszMDBackupName", "")),
        NDRIntField("dwMDVersion", 0),
        NDRIntField("dwMDFlags", 0),
    ]


class Restore_Response(NDRPacket):
    fields_desc = [NDRIntField("status", 0)]


class EnumBackups_Request(NDRPacket):
    fields_desc = [
        NDRConfFieldListField(
            "pszMDBackupName",
            [],
            NDRShortField("", 0),
            size_is=lambda pkt: pkt.MD_BACKUP_MAX_LEN,
        ),
        NDRIntField("dwMDEnumIndex", 0),
    ]


class EnumBackups_Response(NDRPacket):
    fields_desc = [
        NDRConfFieldListField(
            "pszMDBackupName",
            [],
            NDRShortField("", 0),
            size_is=lambda pkt: pkt.MD_BACKUP_MAX_LEN,
        ),
        NDRIntField("pdwMDVersion", 0),
        NDRPacketField("pftMDBackupTime", PFILETIME(), PFILETIME),
        NDRIntField("status", 0),
    ]


class DeleteBackup_Request(NDRPacket):
    fields_desc = [
        NDRFullPointerField(NDRConfVarStrNullFieldUtf16("pszMDBackupName", "")),
        NDRIntField("dwMDVersion", 0),
    ]


class DeleteBackup_Response(NDRPacket):
    fields_desc = [NDRIntField("status", 0)]


class MInterfacePointer(NDRPacket):
    ALIGNMENT = (4, 8)
    DEPORTED_CONFORMANTS = ["abData"]
    fields_desc = [
        NDRIntField("ulCntData", None, size_of="abData"),
        NDRConfStrLenField(
            "abData", "", size_is=lambda pkt: pkt.ulCntData, conformant_in_struct=True
        ),
    ]


class UnmarshalInterface_Request(NDRPacket):
    fields_desc = []


class UnmarshalInterface_Response(NDRPacket):
    fields_desc = [
        NDRFullPointerField(
            NDRPacketField("piadmbwInterface", MInterfacePointer(), MInterfacePointer)
        ),
        NDRIntField("status", 0),
    ]


class GUID(NDRPacket):
    ALIGNMENT = (4, 4)
    fields_desc = [
        NDRIntField("Data1", 0),
        NDRShortField("Data2", 0),
        NDRShortField("Data3", 0),
        StrFixedLenField("Data4", "", length=8),
    ]


class R_GetServerGuid_Request(NDRPacket):
    fields_desc = []


class R_GetServerGuid_Response(NDRPacket):
    fields_desc = [
        NDRPacketField("pServerGuid", GUID(), GUID),
        NDRIntField("status", 0),
    ]


IMSADMINBASEW_OPNUMS = {  # 0: Opnum0NotUsedOnWire,
    # 1: Opnum1NotUsedOnWire,
    # 2: Opnum2NotUsedOnWire,
    3: DceRpcOp(AddKey_Request, AddKey_Response),
    4: DceRpcOp(DeleteKey_Request, DeleteKey_Response),
    5: DceRpcOp(DeleteChildKeys_Request, DeleteChildKeys_Response),
    6: DceRpcOp(EnumKeys_Request, EnumKeys_Response),
    7: DceRpcOp(CopyKey_Request, CopyKey_Response),
    8: DceRpcOp(RenameKey_Request, RenameKey_Response),
    9: DceRpcOp(R_SetData_Request, R_SetData_Response),
    10: DceRpcOp(R_GetData_Request, R_GetData_Response),
    11: DceRpcOp(DeleteData_Request, DeleteData_Response),
    12: DceRpcOp(R_EnumData_Request, R_EnumData_Response),
    13: DceRpcOp(R_GetAllData_Request, R_GetAllData_Response),
    14: DceRpcOp(DeleteAllData_Request, DeleteAllData_Response),
    15: DceRpcOp(CopyData_Request, CopyData_Response),
    16: DceRpcOp(GetDataPaths_Request, GetDataPaths_Response),
    17: DceRpcOp(OpenKey_Request, OpenKey_Response),
    18: DceRpcOp(CloseKey_Request, CloseKey_Response),
    19: DceRpcOp(ChangePermissions_Request, ChangePermissions_Response),
    20: DceRpcOp(SaveData_Request, SaveData_Response),
    21: DceRpcOp(GetHandleInfo_Request, GetHandleInfo_Response),
    22: DceRpcOp(GetSystemChangeNumber_Request, GetSystemChangeNumber_Response),
    23: DceRpcOp(GetDataSetNumber_Request, GetDataSetNumber_Response),
    24: DceRpcOp(SetLastChangeTime_Request, SetLastChangeTime_Response),
    25: DceRpcOp(GetLastChangeTime_Request, GetLastChangeTime_Response),
    26: DceRpcOp(R_KeyExchangePhase1_Request, R_KeyExchangePhase1_Response),
    27: DceRpcOp(R_KeyExchangePhase2_Request, R_KeyExchangePhase2_Response),
    28: DceRpcOp(Backup_Request, Backup_Response),
    29: DceRpcOp(Restore_Request, Restore_Response),
    30: DceRpcOp(EnumBackups_Request, EnumBackups_Response),
    31: DceRpcOp(DeleteBackup_Request, DeleteBackup_Response),
    32: DceRpcOp(UnmarshalInterface_Request, UnmarshalInterface_Response),
    33: DceRpcOp(R_GetServerGuid_Request, R_GetServerGuid_Response),
}
register_com_interface(
    name="IMSAdminBaseW",
    uuid=uuid.UUID("70B51430-B6CA-11d0-B9B9-00A0C922E750"),
    opnums=IMSADMINBASEW_OPNUMS,
)


class BackupWithPasswd_Request(NDRPacket):
    fields_desc = [
        NDRFullPointerField(NDRConfVarStrNullFieldUtf16("pszMDBackupName", "")),
        NDRIntField("dwMDVersion", 0),
        NDRIntField("dwMDFlags", 0),
        NDRFullPointerField(NDRConfVarStrNullFieldUtf16("pszPasswd", "")),
    ]


class BackupWithPasswd_Response(NDRPacket):
    fields_desc = [NDRIntField("status", 0)]


class RestoreWithPasswd_Request(NDRPacket):
    fields_desc = [
        NDRFullPointerField(NDRConfVarStrNullFieldUtf16("pszMDBackupName", "")),
        NDRIntField("dwMDVersion", 0),
        NDRIntField("dwMDFlags", 0),
        NDRFullPointerField(NDRConfVarStrNullFieldUtf16("pszPasswd", "")),
    ]


class RestoreWithPasswd_Response(NDRPacket):
    fields_desc = [NDRIntField("status", 0)]


class Export_Request(NDRPacket):
    fields_desc = [
        NDRFullPointerField(NDRConfVarStrNullFieldUtf16("pszPasswd", "")),
        NDRFullPointerField(NDRConfVarStrNullFieldUtf16("pszFileName", "")),
        NDRFullPointerField(NDRConfVarStrNullFieldUtf16("pszSourcePath", "")),
        NDRIntField("dwMDFlags", 0),
    ]


class Export_Response(NDRPacket):
    fields_desc = [NDRIntField("status", 0)]


class Import_Request(NDRPacket):
    fields_desc = [
        NDRFullPointerField(NDRConfVarStrNullFieldUtf16("pszPasswd", "")),
        NDRFullPointerField(NDRConfVarStrNullFieldUtf16("pszFileName", "")),
        NDRFullPointerField(NDRConfVarStrNullFieldUtf16("pszSourcePath", "")),
        NDRFullPointerField(NDRConfVarStrNullFieldUtf16("pszDestPath", "")),
        NDRIntField("dwMDFlags", 0),
    ]


class Import_Response(NDRPacket):
    fields_desc = [NDRIntField("status", 0)]


class RestoreHistory_Request(NDRPacket):
    fields_desc = [
        NDRFullPointerField(NDRConfVarStrNullFieldUtf16("pszMDHistoryLocation", "")),
        NDRIntField("dwMDMajorVersion", 0),
        NDRIntField("dwMDMinorVersion", 0),
        NDRIntField("dwMDFlags", 0),
    ]


class RestoreHistory_Response(NDRPacket):
    fields_desc = [NDRIntField("status", 0)]


class EnumHistory_Request(NDRPacket):
    fields_desc = [
        NDRConfFieldListField(
            "pszMDHistoryLocation",
            [],
            NDRShortField("", 0),
            size_is=lambda pkt: pkt.MD_BACKUP_MAX_LEN,
        ),
        NDRIntField("dwMDEnumIndex", 0),
    ]


class EnumHistory_Response(NDRPacket):
    fields_desc = [
        NDRConfFieldListField(
            "pszMDHistoryLocation",
            [],
            NDRShortField("", 0),
            size_is=lambda pkt: pkt.MD_BACKUP_MAX_LEN,
        ),
        NDRIntField("pdwMDMajorVersion", 0),
        NDRIntField("pdwMDMinorVersion", 0),
        NDRPacketField("pftMDHistoryTime", PFILETIME(), PFILETIME),
        NDRIntField("status", 0),
    ]


IMSADMINBASE2W_OPNUMS = {  # 0: Opnum0NotUsedOnWire,
    # 1: Opnum1NotUsedOnWire,
    # 2: Opnum2NotUsedOnWire,
    3: DceRpcOp(AddKey_Request, AddKey_Response),
    4: DceRpcOp(DeleteKey_Request, DeleteKey_Response),
    5: DceRpcOp(DeleteChildKeys_Request, DeleteChildKeys_Response),
    6: DceRpcOp(EnumKeys_Request, EnumKeys_Response),
    7: DceRpcOp(CopyKey_Request, CopyKey_Response),
    8: DceRpcOp(RenameKey_Request, RenameKey_Response),
    9: DceRpcOp(R_SetData_Request, R_SetData_Response),
    10: DceRpcOp(R_GetData_Request, R_GetData_Response),
    11: DceRpcOp(DeleteData_Request, DeleteData_Response),
    12: DceRpcOp(R_EnumData_Request, R_EnumData_Response),
    13: DceRpcOp(R_GetAllData_Request, R_GetAllData_Response),
    14: DceRpcOp(DeleteAllData_Request, DeleteAllData_Response),
    15: DceRpcOp(CopyData_Request, CopyData_Response),
    16: DceRpcOp(GetDataPaths_Request, GetDataPaths_Response),
    17: DceRpcOp(OpenKey_Request, OpenKey_Response),
    18: DceRpcOp(CloseKey_Request, CloseKey_Response),
    19: DceRpcOp(ChangePermissions_Request, ChangePermissions_Response),
    20: DceRpcOp(SaveData_Request, SaveData_Response),
    21: DceRpcOp(GetHandleInfo_Request, GetHandleInfo_Response),
    22: DceRpcOp(GetSystemChangeNumber_Request, GetSystemChangeNumber_Response),
    23: DceRpcOp(GetDataSetNumber_Request, GetDataSetNumber_Response),
    24: DceRpcOp(SetLastChangeTime_Request, SetLastChangeTime_Response),
    25: DceRpcOp(GetLastChangeTime_Request, GetLastChangeTime_Response),
    26: DceRpcOp(R_KeyExchangePhase1_Request, R_KeyExchangePhase1_Response),
    27: DceRpcOp(R_KeyExchangePhase2_Request, R_KeyExchangePhase2_Response),
    28: DceRpcOp(Backup_Request, Backup_Response),
    29: DceRpcOp(Restore_Request, Restore_Response),
    30: DceRpcOp(EnumBackups_Request, EnumBackups_Response),
    31: DceRpcOp(DeleteBackup_Request, DeleteBackup_Response),
    32: DceRpcOp(UnmarshalInterface_Request, UnmarshalInterface_Response),
    33: DceRpcOp(R_GetServerGuid_Request, R_GetServerGuid_Response),
    34: DceRpcOp(BackupWithPasswd_Request, BackupWithPasswd_Response),
    35: DceRpcOp(RestoreWithPasswd_Request, RestoreWithPasswd_Response),
    36: DceRpcOp(Export_Request, Export_Response),
    37: DceRpcOp(Import_Request, Import_Response),
    38: DceRpcOp(RestoreHistory_Request, RestoreHistory_Response),
    39: DceRpcOp(EnumHistory_Request, EnumHistory_Response),
}
register_com_interface(
    name="IMSAdminBase2W",
    uuid=uuid.UUID("8298d101-f992-43b7-8eca-5052d885b995"),
    opnums=IMSADMINBASE2W_OPNUMS,
)


class GetChildPaths_Request(NDRPacket):
    fields_desc = [
        NDRIntField("hMDHandle", 0),
        NDRFullPointerField(NDRConfVarStrNullFieldUtf16("pszMDPath", "")),
        NDRIntField("cchMDBufferSize", None, size_of="pszBuffer"),
        NDRConfStrLenFieldUtf16(
            "pszBuffer", "", size_is=lambda pkt: pkt.cchMDBufferSize
        ),
        NDRFullPointerField(NDRIntField("pcchMDRequiredBufferSize", 0)),
    ]


class GetChildPaths_Response(NDRPacket):
    fields_desc = [
        NDRConfStrLenFieldUtf16(
            "pszBuffer", "", size_is=lambda pkt: pkt.cchMDBufferSize
        ),
        NDRFullPointerField(NDRIntField("pcchMDRequiredBufferSize", 0)),
        NDRIntField("status", 0),
    ]


IMSADMINBASE3W_OPNUMS = {  # 0: Opnum0NotUsedOnWire,
    # 1: Opnum1NotUsedOnWire,
    # 2: Opnum2NotUsedOnWire,
    3: DceRpcOp(AddKey_Request, AddKey_Response),
    4: DceRpcOp(DeleteKey_Request, DeleteKey_Response),
    5: DceRpcOp(DeleteChildKeys_Request, DeleteChildKeys_Response),
    6: DceRpcOp(EnumKeys_Request, EnumKeys_Response),
    7: DceRpcOp(CopyKey_Request, CopyKey_Response),
    8: DceRpcOp(RenameKey_Request, RenameKey_Response),
    9: DceRpcOp(R_SetData_Request, R_SetData_Response),
    10: DceRpcOp(R_GetData_Request, R_GetData_Response),
    11: DceRpcOp(DeleteData_Request, DeleteData_Response),
    12: DceRpcOp(R_EnumData_Request, R_EnumData_Response),
    13: DceRpcOp(R_GetAllData_Request, R_GetAllData_Response),
    14: DceRpcOp(DeleteAllData_Request, DeleteAllData_Response),
    15: DceRpcOp(CopyData_Request, CopyData_Response),
    16: DceRpcOp(GetDataPaths_Request, GetDataPaths_Response),
    17: DceRpcOp(OpenKey_Request, OpenKey_Response),
    18: DceRpcOp(CloseKey_Request, CloseKey_Response),
    19: DceRpcOp(ChangePermissions_Request, ChangePermissions_Response),
    20: DceRpcOp(SaveData_Request, SaveData_Response),
    21: DceRpcOp(GetHandleInfo_Request, GetHandleInfo_Response),
    22: DceRpcOp(GetSystemChangeNumber_Request, GetSystemChangeNumber_Response),
    23: DceRpcOp(GetDataSetNumber_Request, GetDataSetNumber_Response),
    24: DceRpcOp(SetLastChangeTime_Request, SetLastChangeTime_Response),
    25: DceRpcOp(GetLastChangeTime_Request, GetLastChangeTime_Response),
    26: DceRpcOp(R_KeyExchangePhase1_Request, R_KeyExchangePhase1_Response),
    27: DceRpcOp(R_KeyExchangePhase2_Request, R_KeyExchangePhase2_Response),
    28: DceRpcOp(Backup_Request, Backup_Response),
    29: DceRpcOp(Restore_Request, Restore_Response),
    30: DceRpcOp(EnumBackups_Request, EnumBackups_Response),
    31: DceRpcOp(DeleteBackup_Request, DeleteBackup_Response),
    32: DceRpcOp(UnmarshalInterface_Request, UnmarshalInterface_Response),
    33: DceRpcOp(R_GetServerGuid_Request, R_GetServerGuid_Response),
    34: DceRpcOp(BackupWithPasswd_Request, BackupWithPasswd_Response),
    35: DceRpcOp(RestoreWithPasswd_Request, RestoreWithPasswd_Response),
    36: DceRpcOp(Export_Request, Export_Response),
    37: DceRpcOp(Import_Request, Import_Response),
    38: DceRpcOp(RestoreHistory_Request, RestoreHistory_Response),
    39: DceRpcOp(EnumHistory_Request, EnumHistory_Response),
    40: DceRpcOp(GetChildPaths_Request, GetChildPaths_Response),
}
register_com_interface(
    name="IMSAdminBase3W",
    uuid=uuid.UUID("f612954d-3b0b-4c56-9563-227b7be624b4"),
    opnums=IMSADMINBASE3W_OPNUMS,
)


class AppCreate_Request(NDRPacket):
    fields_desc = [
        NDRFullPointerField(NDRConfVarStrNullFieldUtf16("szMDPath", "")),
        NDRSignedIntField("fInProc", 0),
    ]


class AppCreate_Response(NDRPacket):
    fields_desc = [NDRIntField("status", 0)]


class AppDelete_Request(NDRPacket):
    fields_desc = [
        NDRFullPointerField(NDRConfVarStrNullFieldUtf16("szMDPath", "")),
        NDRSignedIntField("fRecursive", 0),
    ]


class AppDelete_Response(NDRPacket):
    fields_desc = [NDRIntField("status", 0)]


class AppUnLoad_Request(NDRPacket):
    fields_desc = [
        NDRFullPointerField(NDRConfVarStrNullFieldUtf16("szMDPath", "")),
        NDRSignedIntField("fRecursive", 0),
    ]


class AppUnLoad_Response(NDRPacket):
    fields_desc = [NDRIntField("status", 0)]


class AppGetStatus_Request(NDRPacket):
    fields_desc = [NDRFullPointerField(NDRConfVarStrNullFieldUtf16("szMDPath", ""))]


class AppGetStatus_Response(NDRPacket):
    fields_desc = [NDRIntField("pdwAppStatus", 0), NDRIntField("status", 0)]


class AppDeleteRecoverable_Request(NDRPacket):
    fields_desc = [
        NDRFullPointerField(NDRConfVarStrNullFieldUtf16("szMDPath", "")),
        NDRSignedIntField("fRecursive", 0),
    ]


class AppDeleteRecoverable_Response(NDRPacket):
    fields_desc = [NDRIntField("status", 0)]


class AppRecover_Request(NDRPacket):
    fields_desc = [
        NDRFullPointerField(NDRConfVarStrNullFieldUtf16("szMDPath", "")),
        NDRSignedIntField("fRecursive", 0),
    ]


class AppRecover_Response(NDRPacket):
    fields_desc = [NDRIntField("status", 0)]


IWAMADMIN_OPNUMS = {  # 0: Opnum0NotUsedOnWire,
    # 1: Opnum1NotUsedOnWire,
    # 2: Opnum2NotUsedOnWire,
    3: DceRpcOp(AppCreate_Request, AppCreate_Response),
    4: DceRpcOp(AppDelete_Request, AppDelete_Response),
    5: DceRpcOp(AppUnLoad_Request, AppUnLoad_Response),
    6: DceRpcOp(AppGetStatus_Request, AppGetStatus_Response),
    7: DceRpcOp(AppDeleteRecoverable_Request, AppDeleteRecoverable_Response),
    8: DceRpcOp(AppRecover_Request, AppRecover_Response),
}
register_dcerpc_interface(
    name="IWamAdmin",
    uuid=uuid.UUID("29822AB7-F302-11D0-9953-00C04FD919C1"),
    version="0.0",
    opnums=IWAMADMIN_OPNUMS,
)


class AppCreate2_Request(NDRPacket):
    fields_desc = [
        NDRFullPointerField(NDRConfVarStrNullFieldUtf16("szMDPath", "")),
        NDRIntField("dwAppMode", 0),
    ]


class AppCreate2_Response(NDRPacket):
    fields_desc = [NDRIntField("status", 0)]


IWAMADMIN2_OPNUMS = {  # 0: Opnum0NotUsedOnWire,
    # 1: Opnum1NotUsedOnWire,
    # 2: Opnum2NotUsedOnWire,
    3: DceRpcOp(AppCreate_Request, AppCreate_Response),
    4: DceRpcOp(AppDelete_Request, AppDelete_Response),
    5: DceRpcOp(AppUnLoad_Request, AppUnLoad_Response),
    6: DceRpcOp(AppGetStatus_Request, AppGetStatus_Response),
    7: DceRpcOp(AppDeleteRecoverable_Request, AppDeleteRecoverable_Response),
    8: DceRpcOp(AppRecover_Request, AppRecover_Response),
    9: DceRpcOp(AppCreate2_Request, AppCreate2_Response),
}
register_dcerpc_interface(
    name="IWamAdmin2",
    uuid=uuid.UUID("29822AB8-F302-11D0-9953-00C04FD919C1"),
    version="0.0",
    opnums=IWAMADMIN2_OPNUMS,
)


class CreateApplication_Request(NDRPacket):
    fields_desc = [
        NDRFullPointerField(NDRConfVarStrNullFieldUtf16("szMDPath", "")),
        NDRIntField("dwAppMode", 0),
        NDRFullPointerField(NDRConfVarStrNullFieldUtf16("szAppPoolId", "")),
        NDRSignedIntField("fCreatePool", 0),
    ]


class CreateApplication_Response(NDRPacket):
    fields_desc = [NDRIntField("status", 0)]


class DeleteApplication_Request(NDRPacket):
    fields_desc = [
        NDRFullPointerField(NDRConfVarStrNullFieldUtf16("szMDPath", "")),
        NDRSignedIntField("fRecursive", 0),
    ]


class DeleteApplication_Response(NDRPacket):
    fields_desc = [NDRIntField("status", 0)]


class CreateApplicationPool_Request(NDRPacket):
    fields_desc = [NDRFullPointerField(NDRConfVarStrNullFieldUtf16("szPool", ""))]


class CreateApplicationPool_Response(NDRPacket):
    fields_desc = [NDRIntField("status", 0)]


class DeleteApplicationPool_Request(NDRPacket):
    fields_desc = [NDRFullPointerField(NDRConfVarStrNullFieldUtf16("szPool", ""))]


class DeleteApplicationPool_Response(NDRPacket):
    fields_desc = [NDRIntField("status", 0)]


class FLAGGED_WORD_BLOB(NDRPacket):
    ALIGNMENT = (4, 8)
    DEPORTED_CONFORMANTS = ["asData"]
    fields_desc = [
        NDRIntField("cBytes", 0),
        NDRIntField("clSize", None, size_of="asData"),
        NDRConfStrLenFieldUtf16(
            "asData", "", size_is=lambda pkt: pkt.clSize, conformant_in_struct=True
        ),
    ]


class EnumerateApplicationsInPool_Request(NDRPacket):
    fields_desc = [NDRFullPointerField(NDRConfVarStrNullFieldUtf16("szPool", ""))]


class EnumerateApplicationsInPool_Response(NDRPacket):
    fields_desc = [
        NDRFullPointerField(
            NDRPacketField("bstrBuffer", FLAGGED_WORD_BLOB(), FLAGGED_WORD_BLOB)
        ),
        NDRIntField("status", 0),
    ]


class RecycleApplicationPool_Request(NDRPacket):
    fields_desc = [NDRFullPointerField(NDRConfVarStrNullFieldUtf16("szPool", ""))]


class RecycleApplicationPool_Response(NDRPacket):
    fields_desc = [NDRIntField("status", 0)]


class GetProcessMode_Request(NDRPacket):
    fields_desc = []


class GetProcessMode_Response(NDRPacket):
    fields_desc = [NDRIntField("pdwMode", 0), NDRIntField("status", 0)]


IIISAPPLICATIONADMIN_OPNUMS = {  # 0: Opnum0NotUsedOnWire,
    # 1: Opnum1NotUsedOnWire,
    # 2: Opnum2NotUsedOnWire,
    3: DceRpcOp(CreateApplication_Request, CreateApplication_Response),
    4: DceRpcOp(DeleteApplication_Request, DeleteApplication_Response),
    5: DceRpcOp(CreateApplicationPool_Request, CreateApplicationPool_Response),
    6: DceRpcOp(DeleteApplicationPool_Request, DeleteApplicationPool_Response),
    7: DceRpcOp(
        EnumerateApplicationsInPool_Request, EnumerateApplicationsInPool_Response
    ),
    8: DceRpcOp(RecycleApplicationPool_Request, RecycleApplicationPool_Response),
    9: DceRpcOp(GetProcessMode_Request, GetProcessMode_Response),
}
register_dcerpc_interface(
    name="IIISApplicationAdmin",
    uuid=uuid.UUID("7C4E1804-E342-483D-A43E-A850CFCC8D18"),
    version="0.0",
    opnums=IIISAPPLICATIONADMIN_OPNUMS,
)


class GetTypeInfoCount_Request(NDRPacket):
    fields_desc = []


class GetTypeInfoCount_Response(NDRPacket):
    fields_desc = [NDRIntField("pctinfo", 0), NDRIntField("status", 0)]


class GetTypeInfo_Request(NDRPacket):
    fields_desc = [NDRIntField("iTInfo", 0), NDRIntField("lcid", 0)]


class GetTypeInfo_Response(NDRPacket):
    fields_desc = [
        NDRFullPointerField(
            NDRPacketField("ppTInfo", MInterfacePointer(), MInterfacePointer)
        ),
        NDRIntField("status", 0),
    ]


class GetIDsOfNames_Request(NDRPacket):
    fields_desc = [
        NDRPacketField("riid", GUID(), GUID),
        NDRConfVarStrLenFieldUtf16("rgszNames", "", size_is=lambda pkt: pkt.cNames),
        NDRIntField("cNames", None, size_of="rgszNames"),
        NDRIntField("lcid", 0),
    ]


class GetIDsOfNames_Response(NDRPacket):
    fields_desc = [
        NDRConfFieldListField(
            "rgDispId", [], NDRSignedIntField("", 0), size_is=lambda pkt: pkt.cNames
        ),
        NDRIntField("status", 0),
    ]


class VARENUM(IntEnum):
    VT_EMPTY = 0
    VT_NULL = 1
    VT_I2 = 2
    VT_I4 = 3
    VT_R4 = 4
    VT_R8 = 5
    VT_CY = 6
    VT_DATE = 7
    VT_BSTR = 8
    VT_DISPATCH = 9
    VT_ERROR = 10
    VT_BOOL = 11
    VT_VARIANT = 12
    VT_UNKNOWN = 13
    VT_DECIMAL = 14
    VT_I1 = 16
    VT_UI1 = 17
    VT_UI2 = 18
    VT_UI4 = 19
    VT_I8 = 20
    VT_UI8 = 21
    VT_INT = 22
    VT_UINT = 23
    VT_VOID = 24
    VT_HRESULT = 25
    VT_PTR = 26
    VT_SAFEARRAY = 27
    VT_CARRAY = 28
    VT_USERDEFINED = 29
    VT_LPSTR = 30
    VT_LPWSTR = 31
    VT_RECORD = 36
    VT_INT_PTR = 37
    VT_UINT_PTR = 38
    VT_ARRAY = 8192
    VT_BYREF = 16384


class CURRENCY(NDRPacket):
    ALIGNMENT = (8, 8)
    fields_desc = [NDRSignedLongField("int64", 0)]


class SF_TYPE(IntEnum):
    SF_ERROR = VARENUM.VT_ERROR
    SF_I1 = VARENUM.VT_I1
    SF_I2 = VARENUM.VT_I2
    SF_I4 = VARENUM.VT_I4
    SF_I8 = VARENUM.VT_I8
    SF_BSTR = VARENUM.VT_BSTR
    SF_UNKNOWN = VARENUM.VT_UNKNOWN
    SF_DISPATCH = VARENUM.VT_DISPATCH
    SF_VARIANT = VARENUM.VT_VARIANT
    SF_RECORD = VARENUM.VT_RECORD
    SF_HAVEIID = VARENUM.VT_UNKNOWN | 32768


class SAFEARR_BSTR(NDRPacket):
    ALIGNMENT = (4, 8)
    fields_desc = [
        NDRIntField("Size", None, size_of="aBstr"),
        NDRRefEmbPointerField(
            NDRConfPacketListField(
                "aBstr",
                [],
                FLAGGED_WORD_BLOB,
                size_is=lambda pkt: pkt.Size,
                ptr_pack=True,
            )
        ),
    ]


class SAFEARR_UNKNOWN(NDRPacket):
    ALIGNMENT = (4, 8)
    fields_desc = [
        NDRIntField("Size", None, size_of="apUnknown"),
        NDRRefEmbPointerField(
            NDRConfPacketListField(
                "apUnknown",
                [],
                MInterfacePointer,
                size_is=lambda pkt: pkt.Size,
                ptr_pack=True,
            )
        ),
    ]


class SAFEARR_DISPATCH(NDRPacket):
    ALIGNMENT = (4, 8)
    fields_desc = [
        NDRIntField("Size", None, size_of="apDispatch"),
        NDRRefEmbPointerField(
            NDRConfPacketListField(
                "apDispatch",
                [],
                MInterfacePointer,
                size_is=lambda pkt: pkt.Size,
                ptr_pack=True,
            )
        ),
    ]


class SAFEARR_VARIANT(NDRPacket):
    ALIGNMENT = (4, 8)
    fields_desc = [
        NDRIntField("Size", None, size_of="aVariant"),
        NDRRefEmbPointerField(
            NDRConfPacketListField(
                "aVariant",
                [],
                NDRRecursiveClass("wireVARIANTStr"),
                size_is=lambda pkt: pkt.Size,
                ptr_pack=True,
            )
        ),
    ]


class wireBRECORDStr(NDRPacket):
    ALIGNMENT = (4, 8)
    fields_desc = [
        NDRIntField("fFlags", 0),
        NDRIntField("clSize", None, size_of="pRecord"),
        NDRFullEmbPointerField(
            NDRPacketField("pRecInfo", MInterfacePointer(), MInterfacePointer)
        ),
        NDRFullEmbPointerField(
            NDRConfStrLenField("pRecord", "", size_is=lambda pkt: pkt.clSize)
        ),
    ]


class SAFEARR_BRECORD(NDRPacket):
    ALIGNMENT = (4, 8)
    fields_desc = [
        NDRIntField("Size", None, size_of="aRecord"),
        NDRRefEmbPointerField(
            NDRConfPacketListField(
                "aRecord",
                [],
                wireBRECORDStr,
                size_is=lambda pkt: pkt.Size,
                ptr_pack=True,
            )
        ),
    ]


class SAFEARR_HAVEIID(NDRPacket):
    ALIGNMENT = (4, 8)
    fields_desc = [
        NDRIntField("Size", None, size_of="apUnknown"),
        NDRRefEmbPointerField(
            NDRConfPacketListField(
                "apUnknown",
                [],
                MInterfacePointer,
                size_is=lambda pkt: pkt.Size,
                ptr_pack=True,
            )
        ),
        NDRPacketField("iid", GUID(), GUID),
    ]


class BYTE_SIZEDARR(NDRPacket):
    ALIGNMENT = (4, 8)
    fields_desc = [
        NDRIntField("clSize", None, size_of="pData"),
        NDRFullEmbPointerField(
            NDRConfStrLenField("pData", "", size_is=lambda pkt: pkt.clSize)
        ),
    ]


class WORD_SIZEDARR(NDRPacket):
    ALIGNMENT = (4, 8)
    fields_desc = [
        NDRIntField("clSize", None, size_of="pData"),
        NDRFullEmbPointerField(
            NDRConfStrLenFieldUtf16("pData", "", size_is=lambda pkt: pkt.clSize)
        ),
    ]


class DWORD_SIZEDARR(NDRPacket):
    ALIGNMENT = (4, 8)
    fields_desc = [
        NDRIntField("clSize", None, size_of="pData"),
        NDRFullEmbPointerField(
            NDRConfFieldListField(
                "pData", [], NDRIntField("", 0), size_is=lambda pkt: pkt.clSize
            )
        ),
    ]


class HYPER_SIZEDARR(NDRPacket):
    ALIGNMENT = (4, 8)
    fields_desc = [
        NDRIntField("clSize", None, size_of="pData"),
        NDRFullEmbPointerField(
            NDRConfFieldListField(
                "pData", [], NDRSignedLongField("", 0), size_is=lambda pkt: pkt.clSize
            )
        ),
    ]


class SAFEARRAYBOUND(NDRPacket):
    ALIGNMENT = (4, 4)
    fields_desc = [NDRIntField("cElements", 0), NDRSignedIntField("lLbound", 0)]


class SAFEARRAY(NDRPacket):
    ALIGNMENT = (4, 8)
    DEPORTED_CONFORMANTS = ["rgsabound"]
    fields_desc = [
        NDRShortField("cDims", None, size_of="rgsabound"),
        NDRShortField("fFeatures", 0),
        NDRIntField("cbElements", 0),
        NDRIntField("cLocks", 0),
        NDRUnionField(
            [
                (
                    NDRPacketField("uArrayStructs", SAFEARR_BSTR(), SAFEARR_BSTR),
                    (
                        (lambda pkt: None == SF_TYPE.SF_BSTR),
                        (lambda _, val: val.tag == SF_TYPE.SF_BSTR),
                    ),
                ),
                (
                    NDRPacketField("uArrayStructs", SAFEARR_UNKNOWN(), SAFEARR_UNKNOWN),
                    (
                        (lambda pkt: None == SF_TYPE.SF_UNKNOWN),
                        (lambda _, val: val.tag == SF_TYPE.SF_UNKNOWN),
                    ),
                ),
                (
                    NDRPacketField(
                        "uArrayStructs", SAFEARR_DISPATCH(), SAFEARR_DISPATCH
                    ),
                    (
                        (lambda pkt: None == SF_TYPE.SF_DISPATCH),
                        (lambda _, val: val.tag == SF_TYPE.SF_DISPATCH),
                    ),
                ),
                (
                    NDRPacketField("uArrayStructs", SAFEARR_VARIANT(), SAFEARR_VARIANT),
                    (
                        (lambda pkt: None == SF_TYPE.SF_VARIANT),
                        (lambda _, val: val.tag == SF_TYPE.SF_VARIANT),
                    ),
                ),
                (
                    NDRPacketField("uArrayStructs", SAFEARR_BRECORD(), SAFEARR_BRECORD),
                    (
                        (lambda pkt: None == SF_TYPE.SF_RECORD),
                        (lambda _, val: val.tag == SF_TYPE.SF_RECORD),
                    ),
                ),
                (
                    NDRPacketField("uArrayStructs", SAFEARR_HAVEIID(), SAFEARR_HAVEIID),
                    (
                        (lambda pkt: None == SF_TYPE.SF_HAVEIID),
                        (lambda _, val: val.tag == SF_TYPE.SF_HAVEIID),
                    ),
                ),
                (
                    NDRPacketField("uArrayStructs", BYTE_SIZEDARR(), BYTE_SIZEDARR),
                    (
                        (lambda pkt: None == SF_TYPE.SF_I1),
                        (lambda _, val: val.tag == SF_TYPE.SF_I1),
                    ),
                ),
                (
                    NDRPacketField("uArrayStructs", WORD_SIZEDARR(), WORD_SIZEDARR),
                    (
                        (lambda pkt: None == SF_TYPE.SF_I2),
                        (lambda _, val: val.tag == SF_TYPE.SF_I2),
                    ),
                ),
                (
                    NDRPacketField("uArrayStructs", DWORD_SIZEDARR(), DWORD_SIZEDARR),
                    (
                        (lambda pkt: None == SF_TYPE.SF_I4),
                        (lambda _, val: val.tag == SF_TYPE.SF_I4),
                    ),
                ),
                (
                    NDRPacketField("uArrayStructs", HYPER_SIZEDARR(), HYPER_SIZEDARR),
                    (
                        (lambda pkt: None == SF_TYPE.SF_I8),
                        (lambda _, val: val.tag == SF_TYPE.SF_I8),
                    ),
                ),
            ],
            StrFixedLenField("uArrayStructs", "", length=0),
            align=(4, 8),
            switch_fmt=("I", "I"),
        ),
        NDRConfPacketListField(
            "rgsabound",
            [],
            SAFEARRAYBOUND,
            size_is=lambda pkt: pkt.cDims,
            conformant_in_struct=True,
        ),
    ]


class DECIMAL(NDRPacket):
    ALIGNMENT = (8, 8)
    fields_desc = [
        NDRShortField("wReserved", 0),
        NDRSignedByteField("scale", 0),
        NDRSignedByteField("sign", 0),
        NDRIntField("Hi32", 0),
        NDRLongField("Lo64", 0),
    ]


class wireVARIANTStr(NDRPacket):
    ALIGNMENT = (8, 8)
    fields_desc = [
        NDRIntField("clSize", 0),
        NDRIntField("rpcReserved", 0),
        NDRShortField("vt", 0),
        NDRShortField("wReserved1", 0),
        NDRShortField("wReserved2", 0),
        NDRShortField("wReserved3", 0),
        NDRUnionField(
            [
                (
                    NDRSignedLongField("_varUnion", 0),
                    (
                        (lambda pkt: getattr(pkt, "vt", None) == VARENUM.VT_I8),
                        (lambda _, val: val.tag == VARENUM.VT_I8),
                    ),
                ),
                (
                    NDRSignedIntField("_varUnion", 0),
                    (
                        (lambda pkt: getattr(pkt, "vt", None) == VARENUM.VT_I4),
                        (lambda _, val: val.tag == VARENUM.VT_I4),
                    ),
                ),
                (
                    NDRSignedByteField("_varUnion", 0),
                    (
                        (lambda pkt: getattr(pkt, "vt", None) == VARENUM.VT_UI1),
                        (lambda _, val: val.tag == VARENUM.VT_UI1),
                    ),
                ),
                (
                    NDRSignedShortField("_varUnion", 0),
                    (
                        (lambda pkt: getattr(pkt, "vt", None) == VARENUM.VT_I2),
                        (lambda _, val: val.tag == VARENUM.VT_I2),
                    ),
                ),
                (
                    NDRIEEEFloatField("_varUnion", 0),
                    (
                        (lambda pkt: getattr(pkt, "vt", None) == VARENUM.VT_R4),
                        (lambda _, val: val.tag == VARENUM.VT_R4),
                    ),
                ),
                (
                    NDRIEEEDoubleField("_varUnion", 0),
                    (
                        (lambda pkt: getattr(pkt, "vt", None) == VARENUM.VT_R8),
                        (lambda _, val: val.tag == VARENUM.VT_R8),
                    ),
                ),
                (
                    NDRSignedShortField("_varUnion", 0),
                    (
                        (lambda pkt: getattr(pkt, "vt", None) == VARENUM.VT_BOOL),
                        (lambda _, val: val.tag == VARENUM.VT_BOOL),
                    ),
                ),
                (
                    NDRSignedIntField("_varUnion", 0),
                    (
                        (lambda pkt: getattr(pkt, "vt", None) == VARENUM.VT_ERROR),
                        (lambda _, val: val.tag == VARENUM.VT_ERROR),
                    ),
                ),
                (
                    NDRPacketField("_varUnion", CURRENCY(), CURRENCY),
                    (
                        (lambda pkt: getattr(pkt, "vt", None) == VARENUM.VT_CY),
                        (lambda _, val: val.tag == VARENUM.VT_CY),
                    ),
                ),
                (
                    NDRIEEEDoubleField("_varUnion", 0),
                    (
                        (lambda pkt: getattr(pkt, "vt", None) == VARENUM.VT_DATE),
                        (lambda _, val: val.tag == VARENUM.VT_DATE),
                    ),
                ),
                (
                    NDRFullEmbPointerField(
                        NDRPacketField(
                            "_varUnion", FLAGGED_WORD_BLOB(), FLAGGED_WORD_BLOB
                        )
                    ),
                    (
                        (lambda pkt: getattr(pkt, "vt", None) == VARENUM.VT_BSTR),
                        (lambda _, val: val.tag == VARENUM.VT_BSTR),
                    ),
                ),
                (
                    NDRFullEmbPointerField(
                        NDRPacketField(
                            "_varUnion", MInterfacePointer(), MInterfacePointer
                        )
                    ),
                    (
                        (lambda pkt: getattr(pkt, "vt", None) == VARENUM.VT_UNKNOWN),
                        (lambda _, val: val.tag == VARENUM.VT_UNKNOWN),
                    ),
                ),
                (
                    NDRFullEmbPointerField(
                        NDRPacketField(
                            "_varUnion", MInterfacePointer(), MInterfacePointer
                        )
                    ),
                    (
                        (lambda pkt: getattr(pkt, "vt", None) == VARENUM.VT_DISPATCH),
                        (lambda _, val: val.tag == VARENUM.VT_DISPATCH),
                    ),
                ),
                (
                    NDRFullEmbPointerField(
                        NDRFullEmbPointerField(
                            NDRPacketField("_varUnion", SAFEARRAY(), SAFEARRAY)
                        )
                    ),
                    (
                        (lambda pkt: getattr(pkt, "vt", None) == VARENUM.VT_ARRAY),
                        (lambda _, val: val.tag == VARENUM.VT_ARRAY),
                    ),
                ),
                (
                    NDRFullEmbPointerField(
                        NDRPacketField("_varUnion", wireBRECORDStr(), wireBRECORDStr)
                    ),
                    (
                        (
                            lambda pkt: getattr(pkt, "vt", None)
                            in [
                                VARENUM.VT_RECORD,
                                (VARENUM.VT_RECORD | VARENUM.VT_BYREF),
                            ]
                        ),
                        (
                            lambda _, val: val.tag
                            in [
                                VARENUM.VT_RECORD,
                                (VARENUM.VT_RECORD | VARENUM.VT_BYREF),
                            ]
                        ),
                    ),
                ),
                (
                    NDRFullEmbPointerField(NDRSignedByteField("_varUnion", 0)),
                    (
                        (
                            lambda pkt: getattr(pkt, "vt", None)
                            == (VARENUM.VT_UI1 | VARENUM.VT_BYREF)
                        ),
                        (lambda _, val: val.tag == (VARENUM.VT_UI1 | VARENUM.VT_BYREF)),
                    ),
                ),
                (
                    NDRFullEmbPointerField(NDRSignedShortField("_varUnion", 0)),
                    (
                        (
                            lambda pkt: getattr(pkt, "vt", None)
                            == (VARENUM.VT_I2 | VARENUM.VT_BYREF)
                        ),
                        (lambda _, val: val.tag == (VARENUM.VT_I2 | VARENUM.VT_BYREF)),
                    ),
                ),
                (
                    NDRFullEmbPointerField(NDRSignedIntField("_varUnion", 0)),
                    (
                        (
                            lambda pkt: getattr(pkt, "vt", None)
                            == (VARENUM.VT_I4 | VARENUM.VT_BYREF)
                        ),
                        (lambda _, val: val.tag == (VARENUM.VT_I4 | VARENUM.VT_BYREF)),
                    ),
                ),
                (
                    NDRFullEmbPointerField(NDRSignedLongField("_varUnion", 0)),
                    (
                        (
                            lambda pkt: getattr(pkt, "vt", None)
                            == (VARENUM.VT_I8 | VARENUM.VT_BYREF)
                        ),
                        (lambda _, val: val.tag == (VARENUM.VT_I8 | VARENUM.VT_BYREF)),
                    ),
                ),
                (
                    NDRFullEmbPointerField(NDRIEEEFloatField("_varUnion", 0)),
                    (
                        (
                            lambda pkt: getattr(pkt, "vt", None)
                            == (VARENUM.VT_R4 | VARENUM.VT_BYREF)
                        ),
                        (lambda _, val: val.tag == (VARENUM.VT_R4 | VARENUM.VT_BYREF)),
                    ),
                ),
                (
                    NDRFullEmbPointerField(NDRIEEEDoubleField("_varUnion", 0)),
                    (
                        (
                            lambda pkt: getattr(pkt, "vt", None)
                            == (VARENUM.VT_R8 | VARENUM.VT_BYREF)
                        ),
                        (lambda _, val: val.tag == (VARENUM.VT_R8 | VARENUM.VT_BYREF)),
                    ),
                ),
                (
                    NDRFullEmbPointerField(NDRSignedShortField("_varUnion", 0)),
                    (
                        (
                            lambda pkt: getattr(pkt, "vt", None)
                            == (VARENUM.VT_BOOL | VARENUM.VT_BYREF)
                        ),
                        (
                            lambda _, val: val.tag
                            == (VARENUM.VT_BOOL | VARENUM.VT_BYREF)
                        ),
                    ),
                ),
                (
                    NDRFullEmbPointerField(NDRSignedIntField("_varUnion", 0)),
                    (
                        (
                            lambda pkt: getattr(pkt, "vt", None)
                            == (VARENUM.VT_ERROR | VARENUM.VT_BYREF)
                        ),
                        (
                            lambda _, val: val.tag
                            == (VARENUM.VT_ERROR | VARENUM.VT_BYREF)
                        ),
                    ),
                ),
                (
                    NDRFullEmbPointerField(
                        NDRPacketField("_varUnion", CURRENCY(), CURRENCY)
                    ),
                    (
                        (
                            lambda pkt: getattr(pkt, "vt", None)
                            == (VARENUM.VT_CY | VARENUM.VT_BYREF)
                        ),
                        (lambda _, val: val.tag == (VARENUM.VT_CY | VARENUM.VT_BYREF)),
                    ),
                ),
                (
                    NDRFullEmbPointerField(NDRIEEEDoubleField("_varUnion", 0)),
                    (
                        (
                            lambda pkt: getattr(pkt, "vt", None)
                            == (VARENUM.VT_DATE | VARENUM.VT_BYREF)
                        ),
                        (
                            lambda _, val: val.tag
                            == (VARENUM.VT_DATE | VARENUM.VT_BYREF)
                        ),
                    ),
                ),
                (
                    NDRFullEmbPointerField(
                        NDRFullEmbPointerField(
                            NDRPacketField(
                                "_varUnion", FLAGGED_WORD_BLOB(), FLAGGED_WORD_BLOB
                            )
                        )
                    ),
                    (
                        (
                            lambda pkt: getattr(pkt, "vt", None)
                            == (VARENUM.VT_BSTR | VARENUM.VT_BYREF)
                        ),
                        (
                            lambda _, val: val.tag
                            == (VARENUM.VT_BSTR | VARENUM.VT_BYREF)
                        ),
                    ),
                ),
                (
                    NDRFullEmbPointerField(
                        NDRFullEmbPointerField(
                            NDRPacketField(
                                "_varUnion", MInterfacePointer(), MInterfacePointer
                            )
                        )
                    ),
                    (
                        (
                            lambda pkt: getattr(pkt, "vt", None)
                            == (VARENUM.VT_UNKNOWN | VARENUM.VT_BYREF)
                        ),
                        (
                            lambda _, val: val.tag
                            == (VARENUM.VT_UNKNOWN | VARENUM.VT_BYREF)
                        ),
                    ),
                ),
                (
                    NDRFullEmbPointerField(
                        NDRFullEmbPointerField(
                            NDRPacketField(
                                "_varUnion", MInterfacePointer(), MInterfacePointer
                            )
                        )
                    ),
                    (
                        (
                            lambda pkt: getattr(pkt, "vt", None)
                            == (VARENUM.VT_DISPATCH | VARENUM.VT_BYREF)
                        ),
                        (
                            lambda _, val: val.tag
                            == (VARENUM.VT_DISPATCH | VARENUM.VT_BYREF)
                        ),
                    ),
                ),
                (
                    NDRFullEmbPointerField(
                        NDRFullEmbPointerField(
                            NDRFullEmbPointerField(
                                NDRPacketField("_varUnion", SAFEARRAY(), SAFEARRAY)
                            )
                        )
                    ),
                    (
                        (
                            lambda pkt: getattr(pkt, "vt", None)
                            == (VARENUM.VT_ARRAY | VARENUM.VT_BYREF)
                        ),
                        (
                            lambda _, val: val.tag
                            == (VARENUM.VT_ARRAY | VARENUM.VT_BYREF)
                        ),
                    ),
                ),
                (
                    NDRFullEmbPointerField(
                        NDRFullEmbPointerField(
                            NDRPacketField(
                                "_varUnion", None, NDRRecursiveClass("wireVARIANTStr")
                            )
                        )
                    ),
                    (
                        (
                            lambda pkt: getattr(pkt, "vt", None)
                            == (VARENUM.VT_VARIANT | VARENUM.VT_BYREF)
                        ),
                        (
                            lambda _, val: val.tag
                            == (VARENUM.VT_VARIANT | VARENUM.VT_BYREF)
                        ),
                    ),
                ),
                (
                    NDRSignedByteField("_varUnion", 0),
                    (
                        (lambda pkt: getattr(pkt, "vt", None) == VARENUM.VT_I1),
                        (lambda _, val: val.tag == VARENUM.VT_I1),
                    ),
                ),
                (
                    NDRShortField("_varUnion", 0),
                    (
                        (lambda pkt: getattr(pkt, "vt", None) == VARENUM.VT_UI2),
                        (lambda _, val: val.tag == VARENUM.VT_UI2),
                    ),
                ),
                (
                    NDRIntField("_varUnion", 0),
                    (
                        (lambda pkt: getattr(pkt, "vt", None) == VARENUM.VT_UI4),
                        (lambda _, val: val.tag == VARENUM.VT_UI4),
                    ),
                ),
                (
                    NDRLongField("_varUnion", 0),
                    (
                        (lambda pkt: getattr(pkt, "vt", None) == VARENUM.VT_UI8),
                        (lambda _, val: val.tag == VARENUM.VT_UI8),
                    ),
                ),
                (
                    NDRSignedIntField("_varUnion", 0),
                    (
                        (lambda pkt: getattr(pkt, "vt", None) == VARENUM.VT_INT),
                        (lambda _, val: val.tag == VARENUM.VT_INT),
                    ),
                ),
                (
                    NDRIntField("_varUnion", 0),
                    (
                        (lambda pkt: getattr(pkt, "vt", None) == VARENUM.VT_UINT),
                        (lambda _, val: val.tag == VARENUM.VT_UINT),
                    ),
                ),
                (
                    NDRPacketField("_varUnion", DECIMAL(), DECIMAL),
                    (
                        (lambda pkt: getattr(pkt, "vt", None) == VARENUM.VT_DECIMAL),
                        (lambda _, val: val.tag == VARENUM.VT_DECIMAL),
                    ),
                ),
                (
                    NDRFullEmbPointerField(NDRSignedByteField("_varUnion", 0)),
                    (
                        (
                            lambda pkt: getattr(pkt, "vt", None)
                            == (VARENUM.VT_I1 | VARENUM.VT_BYREF)
                        ),
                        (lambda _, val: val.tag == (VARENUM.VT_I1 | VARENUM.VT_BYREF)),
                    ),
                ),
                (
                    NDRFullEmbPointerField(NDRShortField("_varUnion", 0)),
                    (
                        (
                            lambda pkt: getattr(pkt, "vt", None)
                            == (VARENUM.VT_UI2 | VARENUM.VT_BYREF)
                        ),
                        (lambda _, val: val.tag == (VARENUM.VT_UI2 | VARENUM.VT_BYREF)),
                    ),
                ),
                (
                    NDRFullEmbPointerField(NDRIntField("_varUnion", 0)),
                    (
                        (
                            lambda pkt: getattr(pkt, "vt", None)
                            == (VARENUM.VT_UI4 | VARENUM.VT_BYREF)
                        ),
                        (lambda _, val: val.tag == (VARENUM.VT_UI4 | VARENUM.VT_BYREF)),
                    ),
                ),
                (
                    NDRFullEmbPointerField(NDRLongField("_varUnion", 0)),
                    (
                        (
                            lambda pkt: getattr(pkt, "vt", None)
                            == (VARENUM.VT_UI8 | VARENUM.VT_BYREF)
                        ),
                        (lambda _, val: val.tag == (VARENUM.VT_UI8 | VARENUM.VT_BYREF)),
                    ),
                ),
                (
                    NDRFullEmbPointerField(NDRSignedIntField("_varUnion", 0)),
                    (
                        (
                            lambda pkt: getattr(pkt, "vt", None)
                            == (VARENUM.VT_INT | VARENUM.VT_BYREF)
                        ),
                        (lambda _, val: val.tag == (VARENUM.VT_INT | VARENUM.VT_BYREF)),
                    ),
                ),
                (
                    NDRFullEmbPointerField(NDRIntField("_varUnion", 0)),
                    (
                        (
                            lambda pkt: getattr(pkt, "vt", None)
                            == (VARENUM.VT_UINT | VARENUM.VT_BYREF)
                        ),
                        (
                            lambda _, val: val.tag
                            == (VARENUM.VT_UINT | VARENUM.VT_BYREF)
                        ),
                    ),
                ),
                (
                    NDRFullEmbPointerField(
                        NDRPacketField("_varUnion", DECIMAL(), DECIMAL)
                    ),
                    (
                        (
                            lambda pkt: getattr(pkt, "vt", None)
                            == (VARENUM.VT_DECIMAL | VARENUM.VT_BYREF)
                        ),
                        (
                            lambda _, val: val.tag
                            == (VARENUM.VT_DECIMAL | VARENUM.VT_BYREF)
                        ),
                    ),
                ),
                (
                    StrFixedLenField("_varUnion", "", length=0),
                    (
                        (lambda pkt: getattr(pkt, "vt", None) == VARENUM.VT_EMPTY),
                        (lambda _, val: val.tag == VARENUM.VT_EMPTY),
                    ),
                ),
                (
                    StrFixedLenField("_varUnion", "", length=0),
                    (
                        (lambda pkt: getattr(pkt, "vt", None) == VARENUM.VT_NULL),
                        (lambda _, val: val.tag == VARENUM.VT_NULL),
                    ),
                ),
            ],
            StrFixedLenField("_varUnion", "", length=0),
            align=(2, 8),
            switch_fmt=("H", "H"),
        ),
    ]


class DISPPARAMS(NDRPacket):
    ALIGNMENT = (4, 8)
    fields_desc = [
        NDRFullEmbPointerField(
            NDRConfPacketListField(
                "rgvarg",
                [],
                wireVARIANTStr,
                size_is=lambda pkt: pkt.cArgs,
                ptr_pack=True,
            )
        ),
        NDRFullEmbPointerField(
            NDRConfFieldListField(
                "rgdispidNamedArgs",
                [],
                NDRSignedIntField("", 0),
                size_is=lambda pkt: pkt.cNamedArgs,
            )
        ),
        NDRIntField("cArgs", None, size_of="rgvarg"),
        NDRIntField("cNamedArgs", None, size_of="rgdispidNamedArgs"),
    ]


class EXCEPINFO(NDRPacket):
    ALIGNMENT = (4, 8)
    fields_desc = [
        NDRShortField("wCode", 0),
        NDRShortField("wReserved", 0),
        NDRFullEmbPointerField(
            NDRPacketField("bstrSource", FLAGGED_WORD_BLOB(), FLAGGED_WORD_BLOB)
        ),
        NDRFullEmbPointerField(
            NDRPacketField("bstrDescription", FLAGGED_WORD_BLOB(), FLAGGED_WORD_BLOB)
        ),
        NDRFullEmbPointerField(
            NDRPacketField("bstrHelpFile", FLAGGED_WORD_BLOB(), FLAGGED_WORD_BLOB)
        ),
        NDRIntField("dwHelpContext", 0),
        NDRInt3264Field("pvReserved", 0),
        NDRInt3264Field("pfnDeferredFillIn", 0),
        NDRSignedIntField("scode", 0),
    ]


class Invoke_Request(NDRPacket):
    fields_desc = [
        NDRSignedIntField("dispIdMember", 0),
        NDRPacketField("riid", GUID(), GUID),
        NDRIntField("lcid", 0),
        NDRIntField("dwFlags", 0),
        NDRPacketField("pDispParams", DISPPARAMS(), DISPPARAMS),
        NDRIntField("cVarRef", None, size_of="rgVarRef"),
        NDRConfFieldListField(
            "rgVarRefIdx", [], NDRIntField("", 0), size_is=lambda pkt: pkt.cVarRef
        ),
        NDRConfPacketListField(
            "rgVarRef",
            [],
            wireVARIANTStr,
            size_is=lambda pkt: pkt.cVarRef,
            ptr_pack=True,
        ),
    ]


class Invoke_Response(NDRPacket):
    fields_desc = [
        NDRFullPointerField(
            NDRPacketField("pVarResult", wireVARIANTStr(), wireVARIANTStr)
        ),
        NDRPacketField("pExcepInfo", EXCEPINFO(), EXCEPINFO),
        NDRIntField("pArgErr", 0),
        NDRConfPacketListField(
            "rgVarRef",
            [],
            wireVARIANTStr,
            size_is=lambda pkt: pkt.cVarRef,
            ptr_pack=True,
        ),
        NDRIntField("status", 0),
    ]


IDISPATCH_OPNUMS = {  # 0: Opnum0NotUsedOnWire,
    # 1: Opnum1NotUsedOnWire,
    # 2: Opnum2NotUsedOnWire,
    3: DceRpcOp(GetTypeInfoCount_Request, GetTypeInfoCount_Response),
    4: DceRpcOp(GetTypeInfo_Request, GetTypeInfo_Response),
    5: DceRpcOp(GetIDsOfNames_Request, GetIDsOfNames_Response),
    6: DceRpcOp(Invoke_Request, Invoke_Response),
}
register_com_interface(
    name="IDispatch",
    uuid=uuid.UUID("00020400-0000-0000-C000-000000000046"),
    opnums=IDISPATCH_OPNUMS,
)


class put_IIISCertObj_Opnum7NotUsedOnWire_Request(NDRPacket):
    fields_desc = []


class put_IIISCertObj_Opnum7NotUsedOnWire_Response(NDRPacket):
    fields_desc = [NDRIntField("status", 0)]


class put_IIISCertObj_Opnum8NotUsedOnWire_Request(NDRPacket):
    fields_desc = []


class put_IIISCertObj_Opnum8NotUsedOnWire_Response(NDRPacket):
    fields_desc = [NDRIntField("status", 0)]


class put_IIISCertObj_Opnum9NotUsedOnWire_Request(NDRPacket):
    fields_desc = []


class put_IIISCertObj_Opnum9NotUsedOnWire_Response(NDRPacket):
    fields_desc = [NDRIntField("status", 0)]


class put_IIISCertObj_InstanceName_Request(NDRPacket):
    fields_desc = [NDRPacketField("newVal", FLAGGED_WORD_BLOB(), FLAGGED_WORD_BLOB)]


class put_IIISCertObj_InstanceName_Response(NDRPacket):
    fields_desc = [NDRIntField("status", 0)]


class IsInstalledRemote_Request(NDRPacket):
    fields_desc = []


class IsInstalledRemote_Response(NDRPacket):
    fields_desc = [NDRSignedShortField("retval", 0), NDRIntField("status", 0)]


class IsExportableRemote_Request(NDRPacket):
    fields_desc = []


class IsExportableRemote_Response(NDRPacket):
    fields_desc = [NDRSignedShortField("retval", 0), NDRIntField("status", 0)]


class GetCertInfoRemote_Request(NDRPacket):
    fields_desc = []


class GetCertInfoRemote_Response(NDRPacket):
    fields_desc = [
        NDRFullPointerField(
            NDRPacketField("BinaryVariant", wireVARIANTStr(), wireVARIANTStr)
        ),
        NDRIntField("status", 0),
    ]


class ImportFromBlob_Request(NDRPacket):
    fields_desc = [
        NDRPacketField("InstanceName", FLAGGED_WORD_BLOB(), FLAGGED_WORD_BLOB),
        NDRPacketField("Password", FLAGGED_WORD_BLOB(), FLAGGED_WORD_BLOB),
        NDRSignedShortField("bInstallToMetabase", 0),
        NDRSignedShortField("bAllowExport", 0),
        NDRSignedShortField("bOverWriteExisting", 0),
        NDRIntField("cbSize", None, size_of="pBlobBinary"),
        NDRConfVarStrLenField("pBlobBinary", "", size_is=lambda pkt: pkt.cbSize),
    ]


class ImportFromBlob_Response(NDRPacket):
    fields_desc = [NDRIntField("status", 0)]


class ImportFromBlobGetHash_Request(NDRPacket):
    fields_desc = [
        NDRPacketField("InstanceName", FLAGGED_WORD_BLOB(), FLAGGED_WORD_BLOB),
        NDRPacketField("Password", FLAGGED_WORD_BLOB(), FLAGGED_WORD_BLOB),
        NDRSignedShortField("bInstallToMetabase", 0),
        NDRSignedShortField("bAllowExport", 0),
        NDRSignedShortField("bOverWriteExisting", 0),
        NDRIntField("cbSize", None, size_of="pBlobBinary"),
        NDRConfVarStrLenField("pBlobBinary", "", size_is=lambda pkt: pkt.cbSize),
    ]


class ImportFromBlobGetHash_Response(NDRPacket):
    fields_desc = [
        NDRIntField("pcbCertHashSize", 0),
        NDRFullPointerField(NDRSignedByteField("pCertHash", 0)),
        NDRIntField("status", 0),
    ]


class ExportToBlob_Request(NDRPacket):
    fields_desc = [
        NDRPacketField("InstanceName", FLAGGED_WORD_BLOB(), FLAGGED_WORD_BLOB),
        NDRPacketField("Password", FLAGGED_WORD_BLOB(), FLAGGED_WORD_BLOB),
        NDRSignedShortField("bPrivateKey", 0),
        NDRSignedShortField("bCertChain", 0),
        NDRIntField("pcbSize", 0),
        NDRFullPointerField(NDRConfVarStrNullField("pBlobBinary", "")),
    ]


class ExportToBlob_Response(NDRPacket):
    fields_desc = [
        NDRIntField("pcbSize", 0),
        NDRFullPointerField(NDRConfVarStrNullField("pBlobBinary", "")),
        NDRIntField("status", 0),
    ]


IIISCERTOBJ_OPNUMS = {  # 0: Opnum0NotUsedOnWire,
    # 1: Opnum1NotUsedOnWire,
    # 2: Opnum2NotUsedOnWire,
    3: DceRpcOp(GetTypeInfoCount_Request, GetTypeInfoCount_Response),
    4: DceRpcOp(GetTypeInfo_Request, GetTypeInfo_Response),
    5: DceRpcOp(GetIDsOfNames_Request, GetIDsOfNames_Response),
    6: DceRpcOp(Invoke_Request, Invoke_Response),
    7: DceRpcOp(
        put_IIISCertObj_Opnum7NotUsedOnWire_Request,
        put_IIISCertObj_Opnum7NotUsedOnWire_Response,
    ),
    8: DceRpcOp(
        put_IIISCertObj_Opnum8NotUsedOnWire_Request,
        put_IIISCertObj_Opnum8NotUsedOnWire_Response,
    ),
    9: DceRpcOp(
        put_IIISCertObj_Opnum9NotUsedOnWire_Request,
        put_IIISCertObj_Opnum9NotUsedOnWire_Response,
    ),
    10: DceRpcOp(
        put_IIISCertObj_InstanceName_Request, put_IIISCertObj_InstanceName_Response
    ),
    # 11: Opnum11NotUsedOnWire,
    12: DceRpcOp(IsInstalledRemote_Request, IsInstalledRemote_Response),
    # 13: Opnum13NotUsedOnWire,
    14: DceRpcOp(IsExportableRemote_Request, IsExportableRemote_Response),
    # 15: Opnum15NotUsedOnWire,
    16: DceRpcOp(GetCertInfoRemote_Request, GetCertInfoRemote_Response),
    # 17: Opnum17NotUsedOnWire,
    # 18: Opnum18NotUsedOnWire,
    # 19: Opnum19NotUsedOnWire,
    # 20: Opnum20NotUsedOnWire,
    # 21: Opnum21NotUsedOnWire,
    22: DceRpcOp(ImportFromBlob_Request, ImportFromBlob_Response),
    23: DceRpcOp(ImportFromBlobGetHash_Request, ImportFromBlobGetHash_Response),
    # 24: Opnum24NotUsedOnWire,
    25: DceRpcOp(ExportToBlob_Request, ExportToBlob_Response),
}
register_com_interface(
    name="IIISCertObj",
    uuid=uuid.UUID("BD0C73BC-805B-4043-9C30-9A28D64DD7D2"),
    opnums=IIISCERTOBJ_OPNUMS,
)
