# SPDX-License-Identifier: GPL-2.0-only
# This file is part of Scapy RPC
# See https://scapy.net/ for more information

"""
Generate the .py file frmo the .idl
"""

import argparse
import os
import re
import sys

from datetime import datetime, timezone

from midl_resolve import *

try:
    import black
except ImportError:
    print("BLACK IS REQUIRED TO RUN midl_to_scapy !", file=sys.stderr)
    print("pip install black", file=sys.stderr)
    sys.exit(1)

LICENSE = """# SPDX-License-Identifier: GPL-2.0-only
# This file is part of Scapy RPC
# See https://scapy.net/ for more information
# Copyright (C) Gabriel Potter
"""

BASE = """
%s
import uuid

%s
from scapy.layers.dcerpc import (
    NDRPacket,
    %s
)
"""


def get_base(out):
    fields = ",\n".join(
        x
        for x in sorted(
            [
                "PacketListField",
                "StrFixedLenFieldUtf16",
                "StrFixedLenField",
            ]
        )
        if re.search("(?<!Conf)%s\\(" % x, out)
    )
    return BASE % (
        ("from enum import IntEnum" if "IntEnum" in out else ""),
        ("from scapy.fields import (%s)" % fields) if fields else "",
        ",\n".join(
            x
            for x in sorted(
                set(
                    [
                        # Bare minimum
                        "register_com_interface",
                        "register_dcerpc_interface",
                        "DceRpcOp",
                        # Arrays
                        "NDRVarPacketListField",
                        "NDRConfPacketListField",
                        "NDRConfVarPacketListField",
                        "NDRFieldListField",
                        "NDRConfFieldListField",
                        "NDRConfVarFieldListField",
                        # (yes those 2 don't count as strings)
                        "NDRConfStrLenField",
                        "NDRConfStrLenFieldUtf16",
                        # Strings
                        "NDRConfStrLenField",
                        "NDRConfStrLenFieldUtf16",
                        "NDRVarStrLenField",
                        "NDRVarStrLenFieldUtf16",
                        "NDRConfVarStrLenField",
                        "NDRConfVarStrLenFieldUtf16",
                        "NDRConfVarStrNullField",
                        "NDRConfVarStrNullFieldUtf16",
                        # Union
                        "NDRUnionField",
                        # Misc
                        "NDRContextHandle",
                        "NDRFullEmbPointerField",
                        "NDRFullPointerField",
                        "NDRPacketField",
                        "NDRRecursiveClass",
                        "NDRRefEmbPointerField",
                        # Enums
                        "NDRIntEnumField",
                        "NDRInt3264EnumField",
                    ]
                    + list(SCAPY_FIELDS.values())
                )
            )
            if x in out
        ),
    )


HEADER = '''
"""
RPC definitions for the following interfaces:
- %s
%s"""
'''


def get_header(env):
    return HEADER % (
        "\n- ".join(
            "%s (v%s): %s" % (x.name, x.version, x.uuid)
            for x in env
            if isinstance(x, ScapyInterfaceDefinition)
        ),
        "This file is auto-generated by midl-to-scapy, do not modify.\n",
    )


# For Scapy, we use the following:
# FILTER = {
#     "ept": [2, 3],
#     "IObjectExporter": [3, 5],
#     "drsuapi": [0, 1, 12],
#     "samr": [0, 6],
#     "logon": [4, 26],
#     "srvsvc": [15, 16, 21],
#     "wkssvc": [0, 30],
# }
FILTER = {}

# --- Main


def main(fname):
    # We use stdout.
    # 1. Print license
    print(LICENSE)

    # 2. Port comment from the IDL
    with open(fname, "r") as fd:
        firstline = fd.readline()
        if firstline.startswith("//"):
            print("#" + firstline[2:])

    if FILTER:
        print("# This file is a stripped version ! Use scapy-rpc for the full.")

    # Parse & build AST
    c = Compiler()
    f = c.process_file(fname)
    # Convert into Scapy code
    d = Resolver(f)
    d.resolve_file(fname, filter=FILTER)

    # 3. Build compiled result
    HEADER = get_header(d.environment)
    OUTPUT = "\n".join(x.to_string() for x in d.environment)
    OUTPUT = HEADER + get_base(OUTPUT) + OUTPUT

    # 4. Lint (no formatting is done during output)
    try:
        OUTPUT = black.format_str(OUTPUT, mode=black.Mode())
    except Exception as e:
        print(str(e), file=sys.stderr)
        pass

    # 5. Output linted result
    print(OUTPUT, end="")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Wrong usage.\n python midl_to_scapy.py [files]")
        sys.exit(1)
    else:
        for fname in sys.argv[1:]:
            main(fname)
